name: showermodel
channels:
  - default
  - conda-forge

dependencies:
  - conda-build
  - numpy
  - pandas
  - matplotlib
  - scipy
  - ipython
  # dev dependencies
  - sphinx
  - numpydoc
  - sphinx_rtd_theme
  - sphinx-argparse
  - sphinx-automodapi


