name: showermodel
channels:
  - default
  - conda-forge
dependencies:
# core
  - python
  - conda-build
  - jupyter
  - ipython
  - matplotlib
  - numpy
  - pandas
  - scipy
# development
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - nbsphinx


