name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # make sure we have version info
      - run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python --version
          pip install -U pip setuptools wheel
          python setup.py sdist bdist_wheel
